# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - cyberfuzzapps@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:

  global:

    - CODECOV_TOKEN="283ce38b-c878-4e12-b40f-69857ae5820b"